### ISSUE TITLE
Could not find @ReactModule annotation in com.lufinkey.react.eventemitter.RNEventEmitter

### ISSUE THREAD

**Issue by Dugo03** [lufinkey/react-native-spotify#98]
Getting the following error when running on android:
```
Could not find @ReactModule annotation in com.lufinkey.react.eventemitter.RNEventEmitter

getNameFromAnnotation
    CatalystInstanceImpl.java:444
getNativeModule
    CatalystInstanceImpl.java:433
getNativeModule
    ReactContext.java:119
getMainEventEmitter
    RNEventEmitter.java:41
registerEventEmitterModule
    RNEventEmitter.java:48
__registerAsJSEventEmitter
    RNSpotifyModule.java:1467
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:158
run
    NativeRunnable.java
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:193
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764
```
Occurring on react-native 0.58.4, using gradle 3.2.1, it builds normally, but crashes as soon as the app loads.

Works normally on iOs.

**Comment by marlon-wiprud** [comment]
Also getting this error. Only testing on Android currently.

**Comment by lufinkey** [comment]
Apparently this was a change in react-native `0.5.8`. If you use `0.5.7` for now it should work again. They added a new annotation for react native modules on Android. Should be a 2 line fix, so I'll try to get it done once I get off of work

**Comment by marlon-wiprud** [comment]
Switched to `0.5.7` and the error was resolved. Thanks for the great library!

**Comment by Dugo03** [comment]
Thanks for the quick response, for now I can't downgrade RN, so I'll wait for the patch.

**Comment by lufinkey** [comment]
This update should be published. If you delete you node_modules and package-lock.json and re-run `npm install` it should work again

**Comment by jdnichollsc** [comment]
@lufinkey what's the commit to see the changes?
Thanks in advance!

**Comment by lufinkey** [comment]
[here](https://github.com/lufinkey/react-native-events/commit/93d5c118e7606b116acd1b4183be89378043d860)

**Comment by jdnichollsc** [comment]
thanks for your help @lufinkey! 
I'm reviewing other package but I don't understand what's the issue running the module from Android using the same configuration: https://github.com/jdnichollsc/react-native-dynamic-bundle/blob/master/android/src/main/java/org/mauritsd/reactnativedynamicbundle/RNDynamicBundleModule.java#L20

```
02-22 00:31:45.756 17942-17942/com.modularapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.modularapp, PID: 17942
    java.lang.AssertionError: Could not find module with name RNDynamicBundleModule
        at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:35)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:147)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:433)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:119)
        at com.modularapp.MainActivity$1.onReactContextInitialized(MainActivity.java:39)
        at com.facebook.react.ReactInstanceManager$6.run(ReactInstanceManager.java:1018)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

🤔

**Comment by jdnichollsc** [comment]
Fixed too, thanks!
